### ISSUE TITLE
import rapids_scanpy_funcs

### ISSUE THREAD

**Issue by JBreunig** [clara-parabricks/rapids-single-cell-examples#10]
Looking forward to trying this!  

I'm well-versed in Python/Scanpy/etc. but I wasn't able to figure out how to install the rapids_scanpy_funcs so that they would import in the notebook.  

Tried both the recommended creation of an environment using the yml file and that seemed to work fine except for the error with the rapids functions import.  I also tried with my normal environment and scanpy after installing cuda, rapids, etc.  The other imports were fine until this:

> import rapids_scanpy_funcs

Thanks in advance and apologies if I'm overlooking something simple.

**Comment by avantikalal** [comment]
Hi @JBreunig. `rapids_scanpy_funcs` is a file in the same folder as the notebooks: `https://github.com/clara-parabricks/rapids-single-cell-examples/tree/master/notebooks`. Are you moving the notebooks out of this folder before running them? What is the error message?

**Comment by JBreunig** [comment]
Thanks...I knew I was missing something obvious.  I tend to use Spyder and didn't look in the notebook directory before trying the code.  Apologies.

**Comment by DCGenomics** [comment]
@avantikalal -- It might be worth elevating this very clear answer to the README, I had the same issue and was relieved to see this issue and answer!
